language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devopsmsn
  api_key:
    secure: NEa46ECsEPmNCiM9rgS40Xbk4JBgpCIOxsxThAoGIQKV1uRayiNVZTJnD2LijJXC0tR4DFVRmnWMwv51aUPBbQSKXrZwSQc5GDxEM3PnpXTgPfMIlEUE3XirPI3AFl8jigA90I6C3D1cPCGuEtYxUys6nkDfpVtlKGkgOGTHiVywD1XVG6s3Mxn6zoUE1oP1WWhNwIWHtgnn4dgIw3Acnd9Ca2K168aUtluphakNVIxUwEp+eEHShuKGANVOWtujwTnf8tGRMCyxqJlrKMBKZJID5LNI+xDBgjI2BAHsXsAwvGlBtM6XRCe56Ku14ZsI/ZqRuW18mbmRmkU2MAWfQkNOIfrWnwPRfpCRpaM5MmKM9L4eDlLzZ1ifmNTCkGrLsjLqlzCCwnsAV1Y7bcwXrDoy5q/jj0k+knEJl3Ceq3D2uFun+yp0bAS3E+jen5XOK0BTETQM0d1x54WZ5CvB1UgTGTkexAfWWhzvC0aCl/MhOM5J8PqwEQpeXH+6GawuyAJished7I3B7Ci83Bf8lxa1j+5Yy8zrPZ9pVShq+OpSpDx/05pSseEhU1wrlwye2USpkXy1NyLW6AzYka3EbEyghq3koCAIFy8bQyTSerwlEs/kN5LIU1lxSsosgWT1kdnxo/fT7LJZp+3Ypst3i0b3Fi8sYPtOBilCKHstLM8=
